from .settings import db


class MergeData(db.Model):
    # __tablename__ = 'merge_data'
    id = db.Column(db.Integer,primary_key=True)
    plantcode = db.Column(db.String(length=100))
    warehousecode = db.Column(db.String(length=100))
    destinationcode = db.Column(db.String(length=100))
    subproductcode = db.Column(db.String(length=100))
    capacity = db.Column(db.Float)
    storagecapacity = db.Column(db.Float)
    actualcapacity = db.Column(db.Float)
    distributionchannel = db.Column(db.String(length=100))
    incoterm = db.Column(db.String(length=100))
    demand = db.Column(db.Float)
    minshare = db.Column(db.Float)
    destinationname = db.Column(db.String(length=100))
    salesprice = db.Column(db.Float)
    productcode = db.Column(db.String(length=100))
    subproductname = db.Column(db.String(length=100))
    packtype = db.Column(db.String(length=100))
    statecode = db.Column(db.String(length=100))
    plantname = db.Column(db.String(length=100))
    wdtransportercode = db.Column(db.String(length=100))
    wdfreightcost = db.Column(db.Float)
    wdhandlingcost = db.Column(db.Float)
    pwtransportercode = db.Column(db.String(length=100))
    pwfreightcost = db.Column(db.Float)
    pwhandlingcost = db.Column(db.Float)
    productioncost = db.Column(db.Float)
    packagingcost = db.Column(db.Float)
    warehousename = db.Column(db.String(length=100))
    sourcetype = db.Column(db.String(length=100))
    pdtransportercode = db.Column(db.String(length=100))
    pdfreightcost = db.Column(db.Float)
    pdhandlingcost = db.Column(db.Float)
    benefits = db.Column(db.Float)
    unique_id = db.Column(db.String(length=100))
    unique_name = db.Column(db.String(length=200))


class OptimizeData(db.Model):
    # __tablename__ = 'optimize_data'
    id = db.Column(db.Integer, primary_key=True)
    plantname = db.Column(db.String(length=100))
    warehousename = db.Column(db.String(length=100))
    destinationname = db.Column(db.String(length=100))
    subproductcode = db.Column(db.String(length=100))
    productcode = db.Column(db.String(length=100))
    # transportercode = db.Column(db.String(length=100))
    dispatchquantity = db.Column(db.Float)
    demand = db.Column(db.Float)
    benefits = db.Column(db.Float)
    unique_id = db.Column(db.String(length=100))
    unique_name = db.Column(db.String(length=200))